Create database playstore;
Use playstore;

Create table playstore_apps
(App varchar(100),
Category varchar(100),
Rating	double,
Reviews	 int,
Size	varchar(100),
Installs int,
Type varchar(100),	
Price int,	
Content_Rating	varchar(100),
Genres	varchar(100),
Last_Updated varchar(100),	
Current_Ver	varchar(100),
Android_Ver varchar(100));

Create table playstore_reviews
(App varchar(100),
Translated_Review varchar(200),
Sentiment varchar(10),
Sentiment_Polarity	integer,
Sentiment_Subjectivity integer);

Select * from playstore_apps;

# Q1 Which apps have the highest rating in the given available dataset?
Select App
from playstore_apps
where Rating in (Select max(Rating) from playstore_apps);
 
 # Q2 What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.
Select App, Installs, Reviews
from playstore_apps
where Rating in (Select max(Rating) from playstore_apps)
order by Reviews desc;
 
 # Q3 Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
Select App, Reviews, Category
from playstore_apps
where Reviews in (Select max(Reviews) from playstore_apps);

# Q4 What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)
Select sum(Price) as Total_Revenue from playstore_apps;

# Q5 Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.
Select Category, sum(Installs) as Total_Installs
from playstore_apps
group by Category order by 2 desc limit 1;

# Q6 Which Genre has the most number of published apps?
Select Genres, count(Genres) as total_count
from playstore_apps
group by Genres
order by 2 desc limit 1;

# Q7 Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top(to avoid duplicate results use distinct)
Select distinct App, Installs
from playstore_apps
order by 2 desc;

# Q8 Provide the list of apps that can work on android version 4.0.3 and UP.
Select App from playstore_apps
where Android_Ver ="4.0.3 and up";

# Q9 How many apps from the given data set are free?
Select count(App) as total_free_apps
from playstore_apps
where Type= "Free";

# Also, provide the number of paid apps.
Select count(App) as total_paid_apps
from playstore_apps
where Type= "Paid";

# Q10 Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
Select App, Reviews
from playstore_apps
where Category= "DATING" order by 2 desc limit 1;

# Q14 Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity
Select a.Reviews, r.Sentiment_Polarity,r.Sentiment_Subjectivity
from playstore_apps a join playstore_reviews r
on a.App=r.App
where a.App="Adobe Acrobat Reader" and r.Sentiment="Negative";